[package]
name = "actix-demo"
version = "0.1.0"
authors = ["Grégory OBANOS <gobanos@asylum.fr>"]
edition = "2018"

[dependencies]
actix-web = "*"
actix = "*"
actix-broker = "*"
futures = "*"
rayon = "*"
lazy_static = "*"
rand = "*"